In [1]:
import numpy as np

In [3]:
a=[[11,12,13],[21,22,23],[31,32,33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [4]:
A=np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [5]:
A.ndim

2

In [6]:
A.shape

(3, 3)

In [7]:
A.size

9

In [14]:
x=np.array([[1,0],[0,1]])
y=np.array([[2,1],[1,2]])

In [15]:
z=x+y
z

array([[3, 1],
       [1, 3]])

In [17]:
z=2*x
z

array([[2, 0],
       [0, 2]])